### ISSUE TITLE
Change Notifications

### ISSUE THREAD

**Issue by nkev** [gchaincl/sqlhooks#2]
Great work! I think this could be great for data change notification events to various parts of an application. Is it possible to make the hooks  pre or post execution with the ability to cancel a pre-hook query? For example, a use case might be to stop any query that contains "CREATE TABLE" for users that don't have that permission.

**Comment by gchaincl** [comment]
I agree, this is one of the problem I was trying to solve, to provide a way to notify that some query has been executed.
Cancel a query execution was implemented I removed later, but it is probably a good idea to have it.
This was a proof of concept, I´m working on a better API, but still nothing really usable.
The problem with permissions is not easy to solve using hooks because you need to pass some kind context with extra information, in this case the current user.

**Comment by nkev** [comment]
Thanks. Why not keep it simple and let the calling app be responsible for security?

**Comment by gchaincl** [comment]
Can you elaborate? or give me an example?

**Comment by nkev** [comment]
I'm thinking the sqlhooks would simply be sql hooks. It would be up to the app to determine what to do with an sqlhook callback, including determining if the current user has access to do it. SO going back to my original post, a use case might be to stop any query that contains "CREATE TABLE" for users that don't have that permission. The app would determine whether the current user has the permission to "CREATE TABLE".

**Comment by gchaincl** [comment]
sounds good, if you could draft something that would be cool!
Thanks!

**Comment by gchaincl** [comment]
@nkev I've been working on the new API, please take a look at `v2` branch.

**Comment by nkev** [comment]
will do
